# Generated by Django 3.1 on 2021-02-07 23:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='isianKTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_NIK', models.IntegerField()),
                ('nama_lengkap', models.CharField(max_length=150)),
                ('jenis_kelamin', models.CharField(choices=[('laki-laki', 'LAKI-LAKI'), ('perempuan', 'PEREMPUAN')], max_length=50)),
                ('tanggal_lahir', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')])),
                ('bulan_lahir', models.CharField(choices=[('januari', 'JANUARI'), ('februari', 'FEBRUARI'), ('maret', 'MARET'), ('april', 'APRIL'), ('mei', 'MEI'), ('juni', 'JUNI'), ('juli', 'JULI'), ('agustus', 'AGUSTUS'), ('september', 'SEPTEMBER'), ('oktober', 'OKTOBER'), ('nopember', 'NOVEMBER'), ('desember', 'DESEMBER')], max_length=50)),
                ('tahun_lahir', models.IntegerField(validators=[django.core.validators.MinValueValidator(1920), django.core.validators.MaxValueValidator(2021)])),
                ('agama', models.CharField(choices=[('islam', 'ISLAM'), ('katholik', 'KATHOLIK'), ('kristen', 'KRISTEN'), ('hindu', 'HINDU'), ('konghuchu', 'KONGHUCHU'), ('budha', 'BUDHA'), ('lainnya', 'LAINNYA')], max_length=20)),
                ('status_nikah', models.CharField(choices=[('belum kawin', 'BELUM KAWIN'), ('kawin', 'KAWIN')], max_length=20)),
            ],
        ),
    ]
