# Generated by Django 3.1 on 2021-02-14 03:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrasiKTP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='isianktp',
            name='images',
            field=models.ImageField(null=True, upload_to='gudang foto ktp'),
        ),
        migrations.AlterField(
            model_name='isianktp',
            name='tanggal_lahir',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
